#!/bin/bash

set -e

./install ./tests/carthage
cp ./certificates/cibot.p12 ./tests/carthage/script/certificates

echo "------------------------------------------------------"
echo "----- Testing scripts for Carthage based project -----"
echo "------------------------------------------------------"
cd tests/carthage

echo ""
echo "----- Running script/cibuild -----"
echo ""
script/cibuild

echo ""
echo "----- Running script/build -----"
echo ""
script/build
