#!/bin/bash

set -e

./install ./tests/carthage

echo "------------------------------------------------------"
echo "----- Testing scripts for Carthage based project -----"
echo "------------------------------------------------------"
cd tests/carthage

echo ""
echo "----- Running script/cibuild -----"
echo ""
VERBOSE=1 script/cibuild

echo ""
echo "----- Running script/build -----"
echo ""
VERBOSE=1 script/build
