#!/bin/bash
#
# $1 - Path to iOS project

set -e

generate_env_file ()
{
  echo ""
  echo "Do you want to generate .env file? [N/y]"
  read generate_env_file

  if [ "$generate_env_file" == "y" ]
  then
    while [ -z "$project_name" ]
    do
      echo ""
      echo "Enter the project name:"
      read project_name
    done

    echo ""
    echo "Enter the xcode scheme [$project_name]:"
    read xcode_project_scheme

    echo ""
    echo "Enter 'project' or 'workspace' depending on what you use [project]:"
    read xcode_file
    if [ "$xcode_file" == "workspace" ]
    then
      echo ""
      echo "Enter the xcode workspace file name [$project_name.xcworkspace]:"
      read xcode_workspace_file
      if [ -z "$xcode_workspace_file" ]
      then
        xcode_project_file="$project_name.xcworkspace"
      fi
    else
      echo ""
      echo "Enter the xcode project file name [$project_name.xcodeproj]:"
      read xcode_project_file
      if [ -z "$xcode_project_file" ]
      then
        xcode_project_file="$project_name.xcodeproj"
      fi
    fi

    if [ -z "$xcode_project_scheme" ]
    then
      xcode_project_scheme=$project_name
    fi

    echo "
PROJECT_NAME=$project_name
XCODE_SCHEME=$xcode_project_scheme
XCODE_WORKSPACE=$xcode_workspace_file
XCODE_PROJECT=$xcode_project_file" > "$1/script/.env"

    echo " → '$1/script/.env' successfully generated"
    echo ""
    cat "$1/script/.env"
    echo ""
  else
    echo " → Skipping generation of .env file"
    echo ""
  fi
}

echo ""
echo " → Installing scripts into '$1/script'"
cp -r script $1
echo ""
echo "    ✔  Scripts successfully installed"
echo ""

if [ ! -f "$1/script/.env" ]
then
  generate_env_file
fi

if [ -f $1/Cartfile ]
then
  echo ""
  echo " NOTE: Remember to add your .p12 in '$1/script/certificates'."
  echo " For more information about why this is needed check:"
  echo ""
  echo "   https://github.com/Carthage/Carthage/pull/583"
  echo ""
fi
