#!/bin/bash
scheme_destination ()
{
  shopt -s nocasematch

  case "$1" in
  *iOS) 
    destination="'platform=iOS Simulator,name=iPhone 6,OS=latest'"
    ;;
  *OSX) 
    destination="'platform=OS X'"
    ;;
  *) 
    destination="'platform=iOS Simulator,name=iPhone 6,OS=latest'"
    ;;
  esac

  echo $destination
}