#!/bin/bash

if [ -n "$IOS_OS_VERSION" ] && [ -n "$IOS_SIMULATOR_NAME" ]; then
  IOS_DESTINATION="'platform=iOS Simulator,name=$IOS_SIMULATOR_NAME,OS=$IOS_OS_VERSION'"
fi

scheme_destination ()
{
  shopt -s nocasematch

  case "$1" in
  *iOS) 
    destination=$IOS_DESTINATION
    ;;
  *OSX) 
    destination=$OSX_DESTINATION
    ;;
  *) 
    destination=$IOS_DESTINATION
    ;;
  esac

  echo $destination
}